FROM node:14-alpine

WORKDIR /gatmauel/user-api
COPY . .

RUN apk add --no-cache tzdata 
ENV TZ Asia/Seoul

ENV NODE_ENV production
RUN npm install

RUN chmod +x docker-entrypoint-server.sh
ENTRYPOINT ./docker-entrypoint-server.sh
